name: Scrape Sports Data
on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12PM UTC
  workflow_dispatch: # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: npm install axios cheerio
      
      - name: Run Scraper
        run: node scraper.js
        
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update predictions data'
